import test from 'node:test';
import assert from 'node:assert/strict';
import {blankProject,summarize,validateProject,type Segment} from '../lib/studio.ts';
import {splitSegment,mergeWithNext,recordInterval} from '../lib/segment-edit.ts';

function fixture(){const p=blankProject();const s:Segment={id:'line',text:'Hello world',section:'Verse 1',role:'lead',language:'en',memberIds:[p.members[0].id],tags:[],locked:false,startMs:1000,endMs:11000,timing:'verified'};p.segments=[s];return p;}
test('estimated text split conserves credited duration and leaves the input unchanged',()=>{const p=fixture(),before=structuredClone(p),next=splitSegment(p,'line',5);assert.equal(next.segments.length,2);assert.equal(next.segments[0].endMs,next.segments[1].startMs);assert.ok(next.segments.every(s=>s.timing==='estimated'));assert.equal(summarize(next).total,summarize(p).total);assert.deepEqual(p,before);assert.deepEqual(validateProject(next),next);});
test('explicit split preserves imported or verified provenance but cannot promote estimates',()=>{const p=fixture();assert.equal(splitSegment(p,'line',5,6123).segments[0].timing,'verified');p.segments[0].timing='imported';assert.equal(splitSegment(p,'line',5,6123).segments[0].timing,'imported');p.segments[0].timing='estimated';assert.equal(splitSegment(p,'line',5,6123).segments[1].timing,'estimated');assert.throws(()=>splitSegment(p,'line',5,11000));});
test('split refuses to break an emoji or combining character',()=>{const p=fixture();p.segments[0].text='a👩‍🎤éb';assert.throws(()=>splitSegment(p,'line',3),/完整字符/);assert.throws(()=>splitSegment(p,'line',7),/完整字符/);const next=splitSegment(p,'line',6);assert.deepEqual(next.segments.map(s=>s.text),['a👩‍🎤','éb']);});
test('untimed split keeps only known outer edges without inventing timing',()=>{const p=fixture();delete p.segments[0].endMs;p.segments[0].timing='none';const next=splitSegment(p,'line',5);assert.equal(next.segments[0].startMs,1000);assert.equal(next.segments[0].endMs,undefined);assert.equal(next.segments[1].startMs,undefined);assert.equal(next.segments[1].endMs,undefined);assert.ok(next.segments.every(s=>s.timing==='none'));});
test('merge conserves seconds, retains the first ID and preserves uncertain timing',()=>{const p=fixture(),split=splitSegment(p,'line',5,6000);split.segments[1].timing='imported';const before=structuredClone(split),next=mergeWithNext(split,'line');assert.equal(next.segments.length,1);assert.equal(next.segments[0].id,'line');assert.equal(next.segments[0].text,'Hello\nworld');assert.equal(next.segments[0].timing,'imported');assert.equal(summarize(next).total,summarize(split).total);assert.deepEqual(split,before);});
test('merge rejects differing singers, gaps, overlaps and partial intervals',()=>{const p=splitSegment(fixture(),'line',5,6000);p.segments[1].memberIds=[p.members[1].id];assert.throws(()=>mergeWithNext(p,'line'),/成员/);p.segments[1].memberIds=[p.members[0].id];p.segments[1].startMs=6001;assert.throws(()=>mergeWithNext(p,'line'),/首尾相接/);p.segments[1].startMs=5999;assert.throws(()=>mergeWithNext(p,'line'),/首尾相接/);delete p.segments[1].startMs;assert.throws(()=>mergeWithNext(p,'line'),/补全/);});
test('structure changes and calibration respect locks including the next line',()=>{const p=fixture();p.segments[0].locked=true;assert.throws(()=>splitSegment(p,'line',5),/解锁/);assert.throws(()=>recordInterval(p,'line',0,5000),/解锁/);p.segments[0].locked=false;const next=splitSegment(p,'line',5);next.segments[1].locked=true;assert.throws(()=>mergeWithNext(next,'line'),/解锁/);});
test('recorded timing is exact, atomic and validated',()=>{const p=fixture(),before=structuredClone(p);p.segments[0].timing='estimated';const next=recordInterval(p,'line',1234,5678);assert.equal(next.segments[0].timing,'verified');assert.equal(summarize(next).total,4444);assert.equal(p.segments[0].startMs,before.segments[0].startMs);assert.throws(()=>recordInterval(p,'line',1,1));assert.throws(()=>recordInterval(p,'line',0,3600001));assert.throws(()=>recordInterval(p,'line',0.5,2));});
test('merge of untimed lines stays untimed and split cannot exceed the segment cap',()=>{const p=fixture();delete p.segments[0].startMs;delete p.segments[0].endMs;p.segments[0].timing='none';const split=splitSegment(p,'line',5);assert.equal(mergeWithNext(split,'line').segments[0].timing,'none');p.segments=Array.from({length:500},(_,i)=>({...p.segments[0],id:i?'line-'+i:'line'}));assert.throws(()=>splitSegment(p,'line',5),/500/);});
