import test from 'node:test';
import assert from 'node:assert/strict';
import {allocate,blankProject,csvCell,demoProject,estimateTimes,exportCsv,parseClock,parseLyrics,summarize,validateProject,type Project,type Segment} from '../lib/studio.ts';

const setup=():Project=>{const p=blankProject();p.members[0].id='a';p.members[1].id='b';return p;};
const segment=(id:string,memberIds:string[],startMs?:number,endMs?:number,role:Segment['role']='lead'):Segment=>({id,text:id,memberIds,startMs,endMs,role,section:'Verse 1',language:'en',timing:startMs===undefined?'none':'verified',locked:false,tags:[]});
const values=(p:Project)=>Object.fromEntries(summarize(p).rows.map(r=>[r.member.id,r.value]));

test('participation counts each singer once across overlapping layers',()=>{const p=setup();p.policy='full-participation';p.segments=[segment('lead',['a'],0,10000),segment('harmony',['a'],5000,15000,'harmony'),segment('b',['b'],5000,15000)];assert.deepEqual(values(p),{a:15000,b:10000});assert.equal(summarize(p).coverage,15000);assert.equal(summarize(p).total,25000);});
test('shared overlap splits time among distinct active singers',()=>{const p=setup();p.policy='split-shared';p.segments=[segment('a',['a'],0,10000),segment('b',['b'],5000,15000)];assert.deepEqual(values(p),{a:7500,b:7500});assert.equal(summarize(p).total,15000);});
test('shared overlap does not double-credit one singer in multiple layers',()=>{const p=setup();p.policy='split-shared';p.segments=[segment('a',['a'],0,10000),segment('a harmony',['a'],5000,15000,'harmony'),segment('b',['b'],5000,15000)];assert.deepEqual(values(p),{a:10000,b:5000});});
test('ALL is separate and is not a solo opportunity',()=>{const p=setup();p.segments=[segment('solo',['a'],0,5000),segment('group',['a','b'],5000,15000,'group')];const s=summarize(p);assert.deepEqual(values(p),{a:5000,b:0});assert.equal(s.groupValue,10000);assert.deepEqual(s.missing,[p.members[1].name]);assert.equal(s.fairness,50);});
test('incomplete timing switches the entire comparison to line counts',()=>{const p=setup();p.segments=[segment('timed',['a'],0,8000),segment('untimed',['b'])];assert.equal(summarize(p).useTime,false);assert.deepEqual(values(p),{a:1,b:1});});
test('role filter changes displayed totals and excludes group counts',()=>{const p=setup();p.policy='full-participation';p.segments=[segment('solo',['a'],0,5000),segment('group',['a','b'],5000,15000,'group')];p.includedRoles=['lead'];assert.deepEqual(values(p),{a:5000,b:0});assert.equal(summarize(p).groupValue,0);});
test('disabled performers do not appear in rankings or receive allocation',()=>{const p=setup();p.members[1].enabled=false;p.segments=[segment('one',[])];const result=allocate(p,'style');assert.ok(result.ok);assert.deepEqual(result.segments[0].memberIds,['a']);assert.equal(summarize({...p,segments:result.segments}).rows.length,1);});
test('allocation is deterministic, does not mutate input and preserves locked lines',()=>{const p=demoProject();p.segments[0].locked=true;const before=structuredClone(p);const first=allocate(p,'vocal');assert.ok(first.ok);assert.deepEqual(first.segments[0],p.segments[0]);assert.deepEqual(allocate(p,'vocal'),first);assert.deepEqual(p,before);});
test('cannot disguise insufficient solo lines with a group chorus',()=>{const p=setup();p.segments=[segment('solo',[]),segment('chorus',[],undefined,undefined,'group')];const result=allocate(p,'balanced');assert.equal(result.ok,false);});
test('all-member matching reserves scarce language-compatible lines',()=>{const p=setup();p.rules.strictLanguage=true;p.members[0].languages=['en','ja'];p.members[1].languages=['ja'];p.segments=[segment('English',[]),{...segment('Japanese',[]),language:'ja'}];const result=allocate(p,'style');assert.ok(result.ok);assert.deepEqual(result.segments.map(s=>s.memberIds),[['a'],['b']]);});
test('strict role and tags reject impossible candidates',()=>{const p=setup();p.rules.allMembers=false;p.rules.strictRole=true;p.members.forEach(m=>m.role='vocal');p.segments=[segment('rap',[],undefined,undefined,'rap')];assert.equal(allocate(p,'style').ok,false);p.rules.strictRole=false;p.rules.strictTags=true;p.segments[0].tags=['high'];assert.equal(allocate(p,'style').ok,false);});
test('locked lines conflicting with strict rules fail visibly',()=>{const p=setup();p.rules.strictLanguage=true;p.segments=[{...segment('Japanese',['a']),language:'ja',locked:true}];const result=allocate(p,'style');assert.equal(result.ok,false);if(!result.ok)assert.match(result.errors.join(' '),/锁定句/);});
test('live mode rejects overlapping locked main lines for one performer',()=>{const p=setup();p.rules.allMembers=false;p.rules.live=true;p.segments=[{...segment('first',['a'],0,10000),locked:true},{...segment('second',['a'],5000,15000),locked:true}];assert.equal(allocate(p,'style').ok,false);});
test('chorus rule keeps pre-chorus as solo and converts only chorus',()=>{const p=setup();p.rules.chorusAll=true;p.rules.allMembers=false;p.segments=[{...segment('pre',[]),section:'Pre-chorus'},{...segment('chorus',[]),section:'Chorus'}];const result=allocate(p,'style');assert.ok(result.ok);assert.equal(result.segments[0].role,'lead');assert.equal(result.segments[1].role,'group');assert.deepEqual(result.segments[1].memberIds,['a','b']);});
test('TXT headings keep untimed lyrics and independent roles',()=>{const s=parseLyrics('[Verse 1]\nFirst line\n[Rap]\nSecond line');assert.equal(s.length,2);assert.equal(s[1].role,'rap');assert.equal(s[0].startMs,undefined);assert.deepEqual(s[0].memberIds,[]);});
test('LRC handles multiple tags and offset without fabricating last end',()=>{const s=parseLyrics('[offset:-500]\n[00:01.25][00:03.25]same\n[00:05.00]last');assert.deepEqual(s.map(s=>s.startMs),[750,2750,4500]);assert.deepEqual(s.map(s=>s.endMs),[2750,4500,undefined]);assert.equal(s[0].timing,'estimated');assert.equal(s[2].timing,'none');});
test('SRT preserves millisecond precision and marks imported timing',()=>{const s=parseLyrics('1\n00:00:01,123 --> 00:00:02,456\nOne line\n\n2\n00:00:02,456 --> 00:00:04,000\nNext');assert.equal(s[0].startMs,1123);assert.equal(s[0].endMs,2456);assert.equal(s[0].timing,'imported');assert.equal(parseClock('01:02.345'),62345);});
test('estimated timing covers exact target duration and rejects locked edits',()=>{const s=parseLyrics('a short line\nA substantially longer line');const result=estimateTimes(s,10001);assert.equal(result[0].startMs,0);assert.equal(result[0].endMs,result[1].startMs);assert.equal(result[1].endMs,10001);assert.ok(result.every(s=>s.timing==='estimated'));s[0].locked=true;assert.throws(()=>estimateTimes(s,10001),/锁定/);});
test('project validation rejects invalid references, intervals and prototype names',()=>{const p=setup();p.segments=[segment('s',['unknown'],0,1000)];assert.throws(()=>validateProject(p));p.segments=[segment('s',['a'],1000,500)];assert.throws(()=>validateProject(p));p.segments=[];assert.throws(()=>validateProject({...p,policy:'__proto__'}));assert.throws(()=>validateProject({...p,style:'constructor'}));assert.deepEqual(validateProject(p),p);});
test('CSV protects formula-like content and preserves the selected policy',()=>{const p=setup();p.policy='split-shared';p.segments=[{...segment('s',['a']),text:'=HYPERLINK("test")'}];assert.equal(csvCell('  +SUM(A1)'), '"\'  +SUM(A1)"');assert.match(exportCsv(p),/'=HYPERLINK/);assert.match(exportCsv(p),/共享均分/);});
