import {clock,policyLabels,roleLabels,summarize,timed,type Project} from './studio.ts';
const escape=(s:string)=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
export function download(text:string|Blob,name:string,type='text/plain;charset=utf-8'){const b=typeof text==='string'?new Blob([text],{type}):text;const url=URL.createObjectURL(b);const a=document.createElement('a');a.href=url;a.download=name;a.hidden=true;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
export function fileStem(title:string){return title.replace(/[\\/:*?"<>|]/g,'_').slice(0,100)||'Line-Studio';}
export function lyricHtml(p:Project){return '<!doctype html><html lang="zh-CN"><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+escape(p.title)+'</title><style>body{background:#111516;color:#edf1ec;font:16px/1.7 Arial,sans-serif;max-width:860px;margin:40px auto;padding:0 24px}h1{font-size:36px}section{padding:12px 0;border-bottom:1px solid #313a3a}small{color:#9faeaa;font-size:13px}b{font-weight:500}p{margin:7px 0}</style><h1>'+escape(p.title)+'</h1><p>'+escape(p.artist)+' · '+(p.mode==='redistribution'?'假想分配':'原曲标注')+'</p><p>'+escape(policyLabels[p.policy])+'</p>'+p.segments.map(s=>{const names=s.memberIds.map(id=>p.members.find(m=>m.id===id)?.name??'待分配').join(' / ')||'待分配';const color=s.role==='group'?'#ad9af8':p.members.find(m=>m.id===s.memberIds[0])?.color??'#9faeaa';return '<section><small>'+escape(s.section)+' · '+escape(roleLabels[s.role])+(timed(s)?' · '+clock(s.startMs!,true)+'–'+clock(s.endMs!,true)+' · '+(s.timing==='estimated'?'估算':s.timing==='verified'?'已核对':'待核对'):' · 无时间')+'</small><p style="color:'+color+'"><b>['+escape(names)+']</b> '+escape(s.text)+'</p></section>';}).join('')+'<p><small>Line Studio · 分配稿不代表原唱归属记录。</small></p></html>';}
function stamp(ms:number,ass=false){const h=Math.floor(ms/3600000),m=Math.floor(ms/60000)%60,s=Math.floor(ms/1000)%60;return ass?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${String(Math.floor(ms%1000/10)).padStart(2,'0')}`:`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')},${String(ms%1000).padStart(3,'0')}`;}
export function subtitles(p:Project,format:'srt'|'ass'){
 if(p.segments.some(s=>!timed(s)))throw new Error('请为所有片段填写完整时间，再导出字幕。');
 const rows=[...p.segments].sort((a,b)=>a.startMs!-b.startMs!);const name=(s:typeof rows[number])=>s.memberIds.map(id=>p.members.find(m=>m.id===id)?.name??'待分配').join(' / ')||'待分配';
 if(format==='srt')return rows.map((s,i)=>`${i+1}\n${stamp(s.startMs!)} --> ${stamp(s.endMs!)}\n[${name(s).replace(/[\r\n]/g,' ')}] ${s.text.replace(/<[^>]*>/g,'').replace(/\n/g,' ')}\n`).join('\n');
 const clean=(s:string)=>s.replace(/\\/g,'／').replace(/[{}]/g,'').replace(/\r?\n/g,' ');
 return '[Script Info]\nTitle: '+clean(p.title)+'\nScriptType: v4.00+\nPlayResX: 1920\nPlayResY: 1080\n\n[V4+ Styles]\nFormat: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\nStyle: Default,Arial,48,&H00FFFFFF,&H00FFFFFF,&H00111516,&H00111516,0,0,0,0,100,100,0,0,1,3,0,2,90,90,80,1\n\n[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n'+rows.map(s=>{const color=(p.members.find(m=>m.id===s.memberIds[0])?.color??'#ad9af8').slice(1);const bgr=color.slice(4,6)+color.slice(2,4)+color.slice(0,2);return `Dialogue: 0,${stamp(s.startMs!,true)},${stamp(s.endMs!,true)},Default,,0,0,0,,{\\c&H${bgr}&}[${clean(name(s))}] ${clean(s.text)}`;}).join('\n');
}
export function exportPng(p:Project,onReady?:(blob:Blob,name:string)=>void){const stats=summarize(p);const rows=stats.rows;const w=1000,h=280+rows.length*68+(p.policy==='group-separate'?64:0);const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const c=canvas.getContext('2d');if(!c)throw new Error('此浏览器无法生成图片。');
 c.fillStyle='#111516';c.fillRect(0,0,w,h);c.fillStyle='#8ae9c4';c.font='16px Arial';c.fillText('LINE STUDIO',52,48);c.fillStyle='#edf1ec';c.font='bold 38px Arial';let title=p.title;while(c.measureText(title).width>w-104)title=title.slice(0,-2)+'…';c.fillText(title,52,104);c.font='16px Arial';c.fillStyle='#9faeaa';c.fillText(`${p.mode==='redistribution'?'假想分配':'原曲标注'} · ${policyLabels[p.policy]} · ${stats.useTime?(stats.estimated?'估算秒数':stats.unverified?'导入时间，待核对':'已核对时间'):'按句数统计'}`,52,142);
 const max=Math.max(1,...rows.map(r=>r.value));rows.forEach((r,i)=>{const y=190+i*68;c.fillStyle='#9faeaa';c.font='14px Arial';c.fillText(String(i+1).padStart(2,'0'),52,y+15);c.fillStyle=r.member.color;c.font='18px Arial';let name=r.member.name;while(c.measureText(name).width>200)name=name.slice(0,-2)+'…';c.fillText(name,90,y+15);c.fillStyle='#293330';c.fillRect(310,y,450,18);c.fillStyle=r.member.color;c.fillRect(310,y,450*r.value/max,18);c.fillStyle='#edf1ec';c.font='18px monospace';c.fillText(stats.useTime?(r.value/1000).toFixed(1)+' s':r.value.toFixed(1)+' 句',795,y+15);c.fillStyle='#9faeaa';c.font='12px Arial';c.fillText(`${r.share.toFixed(1)}% · ${r.soloLines} 个独唱句`,310,y+41);});let y=190+rows.length*68;if(p.policy==='group-separate'){c.fillStyle='#ad9af8';c.font='18px Arial';c.fillText(`ALL 合唱：${stats.useTime?(stats.groupValue/1000).toFixed(1)+' 秒':stats.groupValue+' 句'}`,90,y+10);y+=60;}c.fillStyle='#9faeaa';c.font='13px Arial';c.fillText('图表反映本项目的分配与计秒规则。',52,y+33);canvas.toBlob(b=>{if(b){const name=fileStem(p.title)+'_排行.png';if(onReady)onReady(b,name);else download(b,name);}},'image/png');}
